---
abstract: 'Nest tasks w/ indented output and pre/post headers'
author:
  - 'Daniel Muey <http://drmuey.com/cpan_contact.pl>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150001'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Task
no_index:
  directory:
    - t
    - inc
requires:
  IPC::Open3::Utils: '0'
  Test::More: '0'
  Test::Trap: '0'
  Text::OutputFilter: '0'
  Tie::Handle::Base: '0'
resources:
  bugtracker: https://github.com/drmuey/p5-App-Task/issues
  repository: https://github.com/drmuey/p5-App-Task
version: '0.02'
